// <auto-generated />
using System;
using ArticleApp.DAL.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArticleApp.DAL.Migrations
{
    [DbContext(typeof(ArticleAppContext))]
    [Migration("20200923080822_UpdateSubAndParentComment")]
    partial class UpdateSubAndParentComment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArticleApp.Entity.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher. He was one of the reporters, featured in the 1973 book The Boys on the Bus,[2] who covered the 1972 presidential election between Richard Nixon and George McGovern. He won the 1977 Pulitzer Prize for National Reporting for his coverage of the 1976 Presidential campaign and election.[3] Mears retired from his career as a political reporter, editor, and news executive in 2001. In 2016 he joined the Osher Lifelong Learning Institute at Duke University, as a volunteer instructor, teaching classes on election campaigns; he had previously taught undergraduate classes in journalism.[4]",
                            Description = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher.",
                            LastEditDate = new DateTime(2020, 9, 25, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(4955),
                            PublishedDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(4565),
                            State = 2,
                            Title = "Walter Mears",
                            Uid = "fdd2204c-f69d-4bfc-9e61-116461e41cd6",
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Content = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher. He was one of the reporters, featured in the 1973 book The Boys on the Bus,[2] who covered the 1972 presidential election between Richard Nixon and George McGovern. He won the 1977 Pulitzer Prize for National Reporting for his coverage of the 1976 Presidential campaign and election.[3] Mears retired from his career as a political reporter, editor, and news executive in 2001. In 2016 he joined the Osher Lifelong Learning Institute at Duke University, as a volunteer instructor, teaching classes on election campaigns; he had previously taught undergraduate classes in journalism.[4]",
                            Description = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher.",
                            LastEditDate = new DateTime(2020, 9, 25, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6615),
                            PublishedDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6607),
                            State = 2,
                            Title = "Dwight D. Eisenhower",
                            Uid = "48b64056-538a-4f69-869b-df3c353f8ba8",
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Content = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher. He was one of the reporters, featured in the 1973 book The Boys on the Bus,[2] who covered the 1972 presidential election between Richard Nixon and George McGovern. He won the 1977 Pulitzer Prize for National Reporting for his coverage of the 1976 Presidential campaign and election.[3] Mears retired from his career as a political reporter, editor, and news executive in 2001. In 2016 he joined the Osher Lifelong Learning Institute at Duke University, as a volunteer instructor, teaching classes on election campaigns; he had previously taught undergraduate classes in journalism.[4]",
                            Description = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher.",
                            LastEditDate = new DateTime(2020, 9, 25, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6675),
                            PublishedDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6673),
                            State = 2,
                            Title = "Richard Nixon",
                            Uid = "de53928a-664b-455e-b46b-e2e8d8510e1c",
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            Content = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher. He was one of the reporters, featured in the 1973 book The Boys on the Bus,[2] who covered the 1972 presidential election between Richard Nixon and George McGovern. He won the 1977 Pulitzer Prize for National Reporting for his coverage of the 1976 Presidential campaign and election.[3] Mears retired from his career as a political reporter, editor, and news executive in 2001. In 2016 he joined the Osher Lifelong Learning Institute at Duke University, as a volunteer instructor, teaching classes on election campaigns; he had previously taught undergraduate classes in journalism.[4]",
                            Description = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher.",
                            LastEditDate = new DateTime(2020, 9, 25, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6681),
                            PublishedDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6680),
                            State = 2,
                            Title = "Richard Nixon",
                            Uid = "382273a9-dfba-4eee-a07f-c091d0364c38",
                            isActive = true
                        },
                        new
                        {
                            Id = 5,
                            Content = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher. He was one of the reporters, featured in the 1973 book The Boys on the Bus,[2] who covered the 1972 presidential election between Richard Nixon and George McGovern. He won the 1977 Pulitzer Prize for National Reporting for his coverage of the 1976 Presidential campaign and election.[3] Mears retired from his career as a political reporter, editor, and news executive in 2001. In 2016 he joined the Osher Lifelong Learning Institute at Duke University, as a volunteer instructor, teaching classes on election campaigns; he had previously taught undergraduate classes in journalism.[4]",
                            Description = "Walter R. Mears (born January 11, 1935)[1] is an American journalist, author, and teacher.",
                            LastEditDate = new DateTime(2020, 9, 25, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6763),
                            PublishedDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(6762),
                            State = 2,
                            Title = "Richard Nixon",
                            Uid = "c97dbcd6-c82d-47f6-b442-5be95ab737a2",
                            isActive = true
                        });
                });

            modelBuilder.Entity("ArticleApp.Entity.Concrete.ArticleCategory", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArticleCategory");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleId = 3,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("ArticleApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Geography "
                        },
                        new
                        {
                            Id = 3,
                            Name = "History "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mathematics"
                        });
                });

            modelBuilder.Entity("ArticleApp.Entity.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)")
                        .HasMaxLength(600);

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleID");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleID = 1,
                            CommentDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(8218),
                            Content = "Sound Good",
                            Img = "image.png"
                        },
                        new
                        {
                            Id = 2,
                            ArticleID = 1,
                            CommentDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(9088),
                            Content = " Good",
                            Img = "image.png"
                        },
                        new
                        {
                            Id = 3,
                            ArticleID = 2,
                            CommentDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(9111),
                            Content = "Well",
                            Img = "image.png"
                        },
                        new
                        {
                            Id = 4,
                            ArticleID = 2,
                            CommentDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(9112),
                            Content = "Not Good",
                            Img = "image.png"
                        },
                        new
                        {
                            Id = 5,
                            ArticleID = 4,
                            CommentDate = new DateTime(2020, 9, 23, 11, 8, 22, 39, DateTimeKind.Local).AddTicks(9113),
                            Content = "Maybe Sound Good",
                            Img = "image.png"
                        });
                });

            modelBuilder.Entity("ArticleApp.Entity.Concrete.ArticleCategory", b =>
                {
                    b.HasOne("ArticleApp.Entity.Concrete.Article", "Article")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArticleApp.Entity.Concrete.Category", "Category")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArticleApp.Entity.Concrete.Comment", b =>
                {
                    b.HasOne("ArticleApp.Entity.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArticleApp.Entity.Concrete.Comment", "ParentComment")
                        .WithMany("SubComments")
                        .HasForeignKey("ParentCommentId");
                });
#pragma warning restore 612, 618
        }
    }
}
